services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8181:8080"  # Jenkins web interface
      - "50001:50000" # Jenkins agent communication port
    volumes:
      - jenkins_home:/Users/ahsin/Development/docker_volumes/jenkins_home  # Persist Jenkins data
    networks:
      - jenkins-network

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge