version: '3.8'

services:
  flutter-builder:
    image: centos:7
    container_name: flutter-builder
    working_dir: /app
    volumes:
      - ./flutter-app:/app
    environment:
      - FLUTTER_VERSION=3.27.4
    tmpfs:
      - /tmp
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/kvm
    privileged: true
    entrypoint: /bin/bash
    command: >
      -c "
      yum -y update &&
      yum -y install curl unzip java-1.8.0-openjdk-devel git wget &&
      yum clean all &&
      mkdir -p /opt/flutter &&
      curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_$${FLUTTER_VERSION}-stable.tar.xz | tar -xJ -C /opt/flutter --strip-components=1 &&
      export PATH=\"/opt/flutter/bin:$${PATH}\" &&
      yes | flutter doctor --android-licenses &&
      export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk &&
      export PATH=\"$${JAVA_HOME}/bin:$${PATH}\" &&
      flutter create my_flutter_app &&
      cd my_flutter_app &&
      flutter build apk --release &&
      cp build/app/outputs/apk/release/app-release.apk /app/
      "